id: entsoe-monthly-load-compaction
namespace: data_engineering.entsoe

description: |
  Compaction mensile: Riduce il numero di file Parquet per ottimizzare le performance delle query.
  Utilizza il cluster fisico 'cluster-cdca'.

variables:
  gcp_project_id: "entsoe-electricity-v2"
  bucket_name: "entsoe-data-lake-test5689"
  region: "europe-west4"
  cluster_name: "cluster-cdca"
  target_files: "4"

inputs:
  - id: target_year
    type: STRING
    required: false
    description: "Anno target (yyyy). Se vuoto, usa l'anno del giorno precedente al trigger."
  - id: countries
    type: STRING
    required: true
    defaults: "ALL"
    description: "Lista paesi (es. IT,FR) o ALL"

triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 4 1 * *"
    timezone: "Europe/Rome"

tasks:
  # --- STEP 1: ACCENSIONE CLUSTER ---
  - id: start_dataproc
    type: io.kestra.plugin.gcp.cli.GCloudCLI
    projectId: "{{ vars.gcp_project_id }}"
    serviceAccount: "{{ secret('GCP_CREDS_JSON') }}"
    commands:
      - "gcloud dataproc clusters start {{ vars.cluster_name }} --region={{ vars.region }}"

  # --- STEP 2: ESECUZIONE COMPACTION ---
  - id: compact_load_with_spark
    type: io.kestra.plugin.gcp.cli.GCloudCLI
    projectId: "{{ vars.gcp_project_id }}"
    serviceAccount: "{{ secret('GCP_CREDS_JSON') }}"
    commands:
      - >
        gcloud dataproc jobs submit pyspark 
        gs://{{ vars.bucket_name }}/scripts/entsoe_compact_load.py
        --cluster={{ vars.cluster_name }}
        --region={{ vars.region }}
        --properties="spark.driver.memory=10g,spark.executor.memory=2g,spark.memory.fraction=0.6,spark.sql.shuffle.partitions=20"
        -- 
        "gs://{{ vars.bucket_name }}"
        "{{ inputs.target_year ?? now() | dateAdd(-1, 'DAYS') | date('yyyy') }}"
        "{{ vars.target_files }}"
        --countries "{{ inputs.countries }}"

  # --- STEP 3: SPEGNIMENTO CLUSTER ---
  - id: stop_dataproc
    type: io.kestra.plugin.gcp.cli.GCloudCLI
    projectId: "{{ vars.gcp_project_id }}"
    serviceAccount: "{{ secret('GCP_CREDS_JSON') }}"
    commands:
      - "gcloud dataproc clusters stop {{ vars.cluster_name }} --region={{ vars.region }}"

errors:
  - id: stop_cluster_on_error
    type: io.kestra.plugin.gcp.cli.GCloudCLI
    projectId: "{{ vars.gcp_project_id }}"
    serviceAccount: "{{ secret('GCP_CREDS_JSON') }}"
    commands:
      - "gcloud dataproc clusters stop {{ vars.cluster_name }} --region={{ vars.region }}"
  - id: notify_on_failure
    type: io.kestra.plugin.slack.notifications.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_URL') }}"
    payload: |
      {
        "text": "Compaction fallita! Flow={{ flow.id }}, Anno={{ inputs.target_year ?? now() | dateAdd(-1, 'DAYS') | date('yyyy') }}"
      }